import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from 'next/script';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <link rel="stylesheet" href={`${process.env.NEXT_PUBLIC_COMMON_NAV_URL || 'https://megamind-nav.vercel.app'}/common-nav.css`} />
        <Script
          id="common-nav-webcomponent"
          strategy="afterInteractive"
          type="module"
          src={`${process.env.NEXT_PUBLIC_COMMON_NAV_URL || 'https://megamind-nav.vercel.app'}/webcomponent/nav-component.js`}
          crossOrigin="anonymous"
        />
        {/* @ts-expect-error - custom element defined by the webcomponent script */}
        <engineering-playbook-nav></engineering-playbook-nav>
        {children}
      </body>
    </html>
  );
}
